### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Davidwedel** [lansalot/AgOpenGPS-Tools#2]
![image](https://github.com/lansalot/AgOpenGPS-Tools/assets/94093113/2107c188-4989-4f70-a7b0-2d0a458d6df9)
I get above error on wireshark startup. I'm not sure if it is something I'm doing wrong, or plugin error. 
Wireshark 3.6.2. Running on Linux Mint OS.

And then I don't see anything different in wireshark.

**Comment by lansalot** [comment]
Give the above a go and let me know please? It worked OK for me both in linux and windows, not seeing a reason not to include in main.

**Comment by Davidwedel** [comment]
I'll try it when I get home from work in about 5-6 hours and get back with you.

**Comment by Davidwedel** [comment]
Works. Thanks!
